### PR TITLE
Port of probablistic tries from original ocaml adapton

### PR DESCRIPTION
**Pull request by baxtersa**

### CODE REVIEW

**Comment by baxtersa** [comment]
So, performance of the DCG engine is worse than the Naive engine for one of my two benchmark algorithms (performance is roughly identical for the other).

The results of the `add_dups` benchmark (debug, no optimizations, though release yeilds roughly the same performance ratio) when run on my machine:
```
test add_dups::benchmark_naive_trie ... bench:     777,341 ns/iter (+/- 113,150)
test add_dups::benchmark_dcg_trie   ... bench:   1,171,516 ns/iter (+/- 153,272)
```

Attached are some flamegraphs (svg's) captured of the performance. Notably, the DCG benchmark spends roughly a third of its time in the engine, performing `cell` and `force` operations on `art`s. The naive benchmark spend ony 4% of it's time in unkown functions allocating it appears, but nearly all of the rest of its time is spent in either the benchmark framework or my trie implementation.

This hints to the overhead of the DCG engine as the cause of the performance hit, but I wanted to open this up to get more eyes on the code. Maybe I'm misusing `art`s in a way that causes this overhead needlessly.

[flamegraphs.zip](https://github.com/cuplv/adapton.rust/files/658353/flamegraphs.zip)

**Comment by baxtersa** [comment]
Here are the optimized svgs. It does appear that the time spent in `Trie::` functions is reduced (i.e. fewer samples were recorded), but a larger portion of time was spent in the engine, mostly in `cell` computing equality. Overall, here are the runtimes with optimizations:

```
test add_dups::benchmark_naive_trie ... bench:     117,125 ns/iter (+/- 25,657)
test add_dups::benchmark_dcg_trie   ... bench:     167,226 ns/iter (+/- 26,423)
```
[optimized.zip](https://github.com/cuplv/adapton.rust/files/658429/optimized.zip)

**Comment by baxtersa** [comment]
A note for the above optimized benchmark:

The extra time spent in `cell` is outside of the `Trie` functionality. It's time spent in the benchmark framework wrapping the previous trie in a named articulation before inserting a number into this trie art. 

Removing these wrappers, the DCG engine actually performs equal to the naive engine (still not better), but the time spent in `Trie::extend` increases.

Run 1:
```
test add_dups::benchmark_naive_trie ... bench:      87,864 ns/iter (+/- 7,129)
test add_dups::benchmark_dcg_trie   ... bench:      89,070 ns/iter (+/- 12,866)
```
Run 2:
```
test add_dups::benchmark_naive_trie ... bench:      97,809 ns/iter (+/- 27,869)
test add_dups::benchmark_dcg_trie   ... bench:      90,189 ns/iter (+/- 23,336)
```

**Comment by matthewhammer** [comment]
Can you explain briefly why the `dcg` version should go faster than `naive` for this benchmark?
In other words, why would we expect to see an improvement from building the DCG here?

I think the answer is: We are inserting only three distinct elements into the trie, the number 1, the number 2 and the number 3.  There are 150 instances of these three elements (50 of each), and thus the number of elements in the trie should be three, not 150.  (Can you confirm that this was your expectation?)

Given this setting, what do we expect the `dcg` versus `naive` versions of the engine to do?

If I understand the details of the benchmark code: The `naive` version will allocate fresh articulations for each trie insertion.  By contrast, the `dcg` version will attempt to reuse existing articulations, via *nominal* memoization.  The names given to these articulations will "key" these uses of nominal memoization.

I have a few questions and observations, listed below:

 - Question: Have you tried using the *structural* memoization feature of the engine?  Structural memoization is an alternative to nominal memoization that uses traditional "hash-consing" to reuse allocations of articulations.  You can try it either by setting an environment variable (`ADAPTON_STRUCTURAL`) or by wrapping your `dcg`-using code in the function `structural`: https://github.com/cuplv/adapton.rust/blob/f9563cdad0baad9ade5a61d675cf755c3c151085/src/engine.rs#L1663
I don't know how it will affect the performance of this particular benchmark, but it may be instructive to find that out.

 - Observation: Unlike many typical incremental computing benchmarks, there are no input changes here, and the benchmark only runs the measured loop once.
By contrast, we typically run incremental algorithms twice, or many times:  We run them once on an initial input, and then run again (repeatedly) after each input change.

-  Question: Since I do not see input changes here, there is no benefit from the investment of building the `dcg`, which would ordinarily track what steps of the computation are affected by the input change.  Is there a way we could think of running this benchmark on an input that changes over time?

When and if you try running this on a changing input, you'll want to also use a loop that takes advantage of the unchanging structure of the input list, and uses memoization to skip and reuse the iterations that are not affected by the input change.  In Adapton, that requires using a (balanced) tree representation of your input element sequence, and doing a fold over that representation.  See `tree_of_list` and `tree_fold_seq` for building this tree, and doing a fold over its elements.  Both are defined in the `collections` module.

If you want to see an example of using such balanced tree representations, I think this module may provide some code idioms you can adapt for (1) preparing an input as a list, (2) turning this input into a balanced tree (3) running a fold over this input and (4) repeating this process while prepending new elements to the list from step 1.  These portions are of particular interest:
   - https://github.com/cuplv/adapton.rust/blob/95a5c3c42792152ad9236b12a079ae5794412d78/src/arith_parse.rs#L411
   - https://github.com/cuplv/adapton.rust/blob/95a5c3c42792152ad9236b12a079ae5794412d78/src/arith_parse.rs#L451
That code works correctly, but has some unresolved performance issues that we still haven't debugged since writing it.  However, I don't think that these issues will affect your use of its idoms.  In any case, please let me know if you have questions about what's happening there.  I'm happy to try to help answer them.

**Comment by baxtersa** [comment]
Thanks for taking a look!

You interpreted my intention with that benchmark correctly. The trie should ultimately end up containing three elements, and my assumption was that the DCG would reuse the articulations being inserted, rather than create new ones each iteration, therefore yielding better performance.

I think I see why this is not a typical way, and not necessarily an accurate way, of benchmarking this sort of incremental structure/algorithm. The savings are usually associated with computing over the trie, rather than simply inserting elements that already exist, as this benchmark measures (correct?).

With that being the case, maybe the other benchmark I wrote is more representative of what you would want to measure (I've modified the benchmark since you last looked). In this case, I use a trie to maintain the input, adding the numbers `1..100` sequentially in a loop. After inserting the next element on each iteration, I benchmark a `fold` over the input trie that computes the sum over all of its elements. I implemented a memoizing `fold` and the benchmarks are more like what I would expect:
```
running 4 tests
test tree_benchmarks::benchmark_dcg_tree   ... bench:       6,828 ns/iter (+/- 565)
test tree_benchmarks::benchmark_naive_tree ... bench:     180,503 ns/iter (+/- 4,335)
test trie_input::benchmark_dcg_trie        ... bench:       1,952 ns/iter (+/- 120)
test trie_input::benchmark_naive_trie      ... bench:      16,658 ns/iter (+/- 3,250)
```
`tree_benchmarks::*` run the `fold`ed sum over an adapton `Tree`. It's slower because the benchmark includes the time spent converting the input list to a tree, but this was just a sanity test that the structure of the benchmark yeilded an expected performance boost from the DCG engine. `trie_input::*` runs the same `fold`ed sum over a `Trie`, and rather than keeping the input in a `List` and converting to a `Trie` each iteration, I mutate the input `Trie` directly each iteration.

It has taken me a little while to get used to the `Adapton` programming paradigm, but I think this is more what we would expect the behavior of `dcg` vs. `Naive` to look like.

**Comment by baxtersa** [comment]
Running the above benchmark with `ADAPTON_STRUCTURAL=1`:
```
running 4 tests
test tree_benchmarks::benchmark_dcg_tree   ... bench:       4,865 ns/iter (+/- 125)
test tree_benchmarks::benchmark_naive_tree ... bench:     178,579 ns/iter (+/- 4,100)
test trie_input::benchmark_dcg_trie        ... bench:       9,754 ns/iter (+/- 64)
test trie_input::benchmark_naive_trie      ... bench:      16,613 ns/iter (+/- 3,071)
```

**Pull request merged**
